version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - database_network
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}

  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SECRET_KEY
    entrypoint: ./entrypoint.sh 'development'
    depends_on:
      - db
    volumes:
      - .:/usr/src/core-api/
    networks:
      - database_network
      - redis_network
    environment:
      DEBUG: "true"
      DJANGO_SETTINGS_MODULE: "core.settings.base"
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      REDIS_HOST: ${REDIS_HOST}
      AIRTABLE_API_KEY: ${AIRTABLE_API_KEY}
      AIRTABLE_BASE_ID: ${AIRTABLE_BASE_ID}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      CURRENCY_API_KEY: ${CURRENCY_API_KEY}
    ports:
      - "8000:8000"
volumes:
  db:

networks:
  database_network:
  redis_network:
