# Generated by Django 4.1.5 on 2024-01-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BetHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=100)),
                ("bet", models.IntegerField()),
                ("win_on_bet", models.IntegerField()),
                ("total_bet", models.IntegerField()),
                ("potential_win", models.IntegerField()),
            ],
            options={
                "verbose_name": "Bet History",
                "verbose_name_plural": "Bet History",
            },
        ),
    ]
